export const REGISTER_USER = "REGISTER_USER";

export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const LOAD_USER = "LOAD_USER";
export const FAIL_USER = "FAIL_USER";
export const CURRENT_USER = "CURRENT_USER";

export const GETALLDOCTORS = "GETALLDOCTORS";
export const GETALLClients = "GETALLCLIENTS";

export const GETDOCDETAIL_REQUEST = "GETDOCDETAIL_REQUEST";
export const GETDOCDETAIL_SUCCESS = "GETDOCDETAIL_SUCCESS";
export const GETDOCDETAIL_FAIL = "GETDOCDETAIL_FAIL";

export const FAIL_DOCTOR = "FAIL_DOCTOR";
export const FAIL_CLIENT = "FAIL_CLIENT";

export const FILTER = "FILTER";
export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL";
export const LOG_OUT_CHAT = "LOG_OUT_CHAT";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const DELETE = "DELETE";
export const DELETE_FAIL = "DELETE_FAIL";
